#!/usr/bin/php
<?php

require_once(dirname(__FILE__) . '/library/XfCli/Autoloader.php');
require_once(dirname(__FILE__) . '/library/XfCli/Application.php');
require_once(dirname(__FILE__) . '/library/PHP-CLI/cli.php');

XfCli_Application::initialize();

$xfLibrary = XfCli_Application::xfBaseDir() . DIRECTORY_SEPARATOR . 'library' . DIRECTORY_SEPARATOR;
 
// Initialize the xenforo autoloader
require_once($xfLibrary . 'XenForo/Autoloader.php');
XenForo_Autoloader::getInstance()->setupAutoloader($xfLibrary);
 
// Initialize XenForo App
XenForo_Application::setDebugMode(true);
XenForo_Application::initialize($xfLibrary, XfCli_Application::xfBaseDir());
$dependencies = new XenForo_Dependencies_Public();
$dependencies->preLoadData();
 
unset($xfLibrary);

XfCli_Application::setExceptionHandlers();

new CLI_Xf();